export const uiGalleryTopologySections = [
  {
    id: "28",
    technicalName: "ui.templates.status",
    name: "Status template",
    scope: "UI workspace",
    description: "Documents the standard colored status badge and table pattern.",
  },
  {
    id: "28.1",
    technicalName: "ui.status.preview",
    name: "Status preview",
    scope: "Status template",
    description: "Shows status badges in an operational table.",
  },
  {
    id: "28.2",
    technicalName: "ui.status.usage",
    name: "Status usage",
    scope: "Status template",
    description: "Public status badge API and application-owned values.",
  },
  {
    id: "27",
    technicalName: "ui.templates.masterList",
    name: "Master List template",
    scope: "UI workspace",
    description: "Documents the configurable master list and form.",
  },
  {
    id: "27.1",
    technicalName: "ui.masterList.preview",
    name: "Master List preview",
    scope: "Master List template",
    description: "Interactive table, card, and record form variants.",
  },
  {
    id: "27.1.1",
    technicalName: "ui.masterList.applicationHeader",
    name: "Application header",
    scope: "Master List preview",
    description: "Shows the current master-list title and primary create action.",
  },
  {
    id: "27.1.1.1",
    technicalName: "ui.masterList.title",
    name: "Title",
    scope: "Application header",
    description: "Names the active master list.",
  },
  {
    id: "27.1.1.2",
    technicalName: "ui.masterList.newButton",
    name: "New button",
    scope: "Application header",
    description: "Starts a new master record.",
  },
  {
    id: "27.1.2",
    technicalName: "ui.masterList.searchStrip",
    name: "Search strip",
    scope: "Master List preview",
    description: "Filters the visible records in the current preview.",
  },
  {
    id: "27.1.2.1",
    technicalName: "ui.masterList.searchBar",
    name: "Search bar",
    scope: "Search strip",
    description: "Searches the current master records.",
  },
  {
    id: "27.1.2.2",
    technicalName: "ui.masterList.columnFilter",
    name: "Column filter",
    scope: "Search strip",
    description: "Controls visible table columns.",
  },
  {
    id: "27.1.2.3",
    technicalName: "ui.masterList.quickFilters",
    name: "Quick filters",
    scope: "Search strip",
    description: "Filters high-volume Desk records by their most common fields.",
  },
  {
    id: "27.1.2.4",
    technicalName: "ui.masterList.filterActions",
    name: "Filter actions",
    scope: "Search strip",
    description: "Opens, clears, and sorts the active record filters.",
  },
  {
    id: "27.1.3",
    technicalName: "ui.masterList.dataTable",
    name: "Data table",
    scope: "Master List preview",
    description: "Renders the current records and row actions.",
  },
  {
    id: "27.1.3.1",
    technicalName: "ui.masterList.rowHeader",
    name: "Row header",
    scope: "Data table",
    description: "Labels the data-table columns.",
  },
  {
    id: "27.1.3.2",
    technicalName: "ui.masterList.rows",
    name: "Rows",
    scope: "Data table",
    description: "Displays the current master records.",
  },
  {
    id: "27.1.3.3",
    technicalName: "ui.masterList.filterRow",
    name: "Column filter row",
    scope: "Data table",
    description: "Filters records directly below the table header.",
  },
  {
    id: "27.1.4",
    technicalName: "ui.masterList.pagination",
    name: "Pagination",
    scope: "Master List preview",
    description: "Controls page size and record navigation.",
  },
  {
    id: "27.1.4.1",
    technicalName: "ui.masterList.pageSize",
    name: "Page size",
    scope: "Pagination",
    description: "Controls the number of records shown per page.",
  },
  {
    id: "27.1.4.2",
    technicalName: "ui.masterList.pageNavigation",
    name: "Page navigation",
    scope: "Pagination",
    description: "Moves between record pages.",
  },
  {
    id: "27.1.4.3",
    technicalName: "ui.masterList.loadMore",
    name: "Load more",
    scope: "Pagination",
    description: "Requests the next batch of master records.",
  },
  {
    id: "27.2",
    technicalName: "ui.masterList.usage",
    name: "Master List usage",
    scope: "Master List template",
    description: "Public API and application data ownership.",
  },
  {
    id: "26",
    technicalName: "ui.execution.documentation",
    name: "Execution Status",
    scope: "UI workspace",
    description: "Documents observed execution status.",
  },
  {
    id: "26.1",
    technicalName: "ui.execution.preview",
    name: "Execution preview",
    scope: "Execution Status",
    description: "Interactive state and motion specimen.",
  },
  {
    id: "26.2",
    technicalName: "ui.execution.usage",
    name: "Execution usage",
    scope: "Execution Status",
    description: "Public properties and ownership.",
  },
  {
    id: "29",
    technicalName: "ui.blocks.mascot",
    name: "Mascot",
    scope: "UI workspace",
    description: "Documents the shared pointer-aware mascot runtime and sprite-sheet contract.",
  },
  {
    id: "29.1",
    technicalName: "ui.mascot.preview",
    name: "Mascot preview",
    scope: "Mascot",
    description: "Interactive cursor tracking and click reaction specimen.",
  },
  {
    id: "29.2",
    technicalName: "ui.mascot.usage",
    name: "Mascot usage",
    scope: "Mascot",
    description: "Public two-atlas API and application-owned asset guidance.",
  },
  {
    id: "30",
    technicalName: "ui.blocks.appHeader",
    name: "App Header",
    scope: "UI workspace",
    description: "Documents the shared page-level header contract and its three arrangements.",
  },
  {
    id: "30.1",
    technicalName: "ui.appHeader.preview",
    name: "App Header preview",
    scope: "App Header",
    description: "Interactive preview of breadcrumb, title, and resource header variants.",
  },
  {
    id: "30.2",
    technicalName: "ui.appHeader.usage",
    name: "App Header usage",
    scope: "App Header",
    description: "Typed dynamic slots for page context, controls, links, and actions.",
  },
  {
    id: "20",
    technicalName: "ui.overview.showcase",
    name: "UI overview",
    scope: "UI workspace",
    description: "Introduces the shared design system through reusable component compositions.",
  },
  {
    id: "21",
    technicalName: "ui.layouts.documentation",
    name: "Layout documentation",
    scope: "UI workspace",
    description: "Documents one shared layout with preview, usage, code, and ownership guidance.",
  },
  {
    id: "21.1",
    technicalName: "ui.layouts.preview",
    name: "Layout preview",
    scope: "Layout documentation",
    description: "Shows a scaled visual composition of the selected layout.",
  },
  {
    id: "21.2",
    technicalName: "ui.layouts.usageCode",
    name: "Layout usage code",
    scope: "Layout documentation",
    description: "Explains MDI Main ownership and provides a copyable TypeScript example.",
  },
  {
    id: "22",
    technicalName: "ui.blocks.tableDocumentation",
    name: "Table block documentation",
    scope: "UI workspace",
    description: "Documents a shared component with its live result and public usage.",
  },
  {
    id: "22.1",
    technicalName: "ui.table.livePreview",
    name: "Live table",
    scope: "Table block documentation",
    description: "Renders ten sample records through the centralized table block.",
  },
  {
    id: "22.2",
    technicalName: "ui.table.usageCode",
    name: "Table usage code",
    scope: "Table block documentation",
    description: "Provides a copyable table composition example.",
  },
  {
    id: "23",
    technicalName: "ui.blocks.formDocumentation",
    name: "Form block documentation",
    scope: "UI workspace",
    description: "Documents the shared form composition and application-owned field content.",
  },
  {
    id: "23.1",
    technicalName: "ui.form.livePreview",
    name: "Live form",
    scope: "Form block documentation",
    description: "Renders tabs, lookup fields, active state, and form actions.",
  },
  {
    id: "23.2",
    technicalName: "ui.form.usageCode",
    name: "Form usage code",
    scope: "Form block documentation",
    description: "Provides a copyable form composition example.",
  },
  {
    id: "24",
    technicalName: "ui.components.documentation",
    name: "Component documentation",
    scope: "UI workspace",
    description: "Documents every shared primitive through the standard live page pattern.",
  },
  {
    id: "24.1",
    technicalName: "ui.components.livePreview",
    name: "Live component preview",
    scope: "Component documentation",
    description: "Renders a live package-owned specimen for the selected component category.",
  },
  {
    id: "24.2",
    technicalName: "ui.components.usageCode",
    name: "Component usage code",
    scope: "Component documentation",
    description: "Provides the selected component public import path.",
  },
  {
    id: "25",
    technicalName: "ui.pages.documentation",
    name: "Page documentation",
    scope: "UI workspace",
    description: "Documents reusable application pages and their owned variants.",
  },
  {
    id: "25.1",
    technicalName: "ui.pages.livePreview",
    name: "Live page preview",
    scope: "Page documentation",
    description: "Renders the selected package-owned page variant.",
  },
  {
    id: "25.2",
    technicalName: "ui.pages.usageCode",
    name: "Page usage code",
    scope: "Page documentation",
    description: "Explains application binding and provides the public import path.",
  },
] as const;
